### PR TITLE
Added the missed dependency

### PR DESCRIPTION
**Pull request by zaleslaw**
I suggest the simple fixe for the [issue ](https://github.com/tensorflow/java-models/issues/4)

### CODE REVIEW

**Comment by zaleslaw** [comment]
@googlebot I signed it!

**Comment by zaleslaw** [comment]
@karllessard please review

**Comment by saudet** [comment]
That should get resolved transitively. You're not trying to use M2Eclipse by any chance? If so, don't use that.

**Comment by karllessard** [comment]
Yes I was about to say the same, it looks like you have a transitive dependency problem in general, I also think that is the case #6 . Can you double-check your Maven settings or check that transitive dependencies are only broken for TensorFlow in your workspace?

**Comment by zaleslaw** [comment]
@karllessard @saudet I don't use Eclipse (I use IDEA instead). Seems like protobuf and tools transitive dependecies are not downloaded on my machine. But in opposite side, no problems with transitive dependencies for old legacy examples. Does protobuf and tools are really included as transitive dependencies? (sorry for double-check, guys)

**Comment by karllessard** [comment]
I just commented on this [here](https://github.com/tensorflow/java-models/issues/6#issuecomment-629906342), effectively the snapshot repository was missing in the pom, keep me posted if that fixes all your problems with missing dependencies.

**Comment by karllessard** [comment]
See #4 , it seems to be a bug related to IDEA. Closing this PR for now.

**Pull request closed without merging**
